spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/slideshow_db
    username: slideshow_user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: slideshow

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs